# Copyright (C) 2017  Kouhei Sutou <kou@clear-code.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

- hosts: servers
  become: yes
  tasks:
    - name: Set timezone
      # Ansible 2.2 is required
      # timezone:
      #   name: Asia/Tokyo
      command: timedatectl set-timezone Asia/Tokyo
    - name: Enable NTP
      command: timedatectl set-ntp true
    - name: Install required packages
      apt:
        name: "{{ item }}"
      with_items:
        - vsftpd
        - fonts-noto-cjk
        - chromium-browser
    - name: Create empty passphrase key
      command: ssh-keygen -f /home/vagrant/.ssh/login.rsa -t rsa -N ''
    - name: Set proper ownership to key
      file:
        path: "{{ item }}"
        owner: vagrant
        group: vagrant
        mode: 0600
      with_items:
        - /home/vagrant/.ssh/login.rsa
        - /home/vagrant/.ssh/login.rsa.pub
    - name: Set empty passphrase key as authorized
      shell: cat /home/vagrant/.ssh/login.rsa.pub >> /home/vagrant/.ssh/authorized_keys
    - name: Setup configuration file
      copy:
        src: etc/default/{{ item }}
        dest: /etc/default/{{ item }}
      with_items:
        - browser-protocol
    - name: Copy vsftpd configuration file
      copy:
        src: etc/{{ item }}
        dest: /etc/{{ item }}
      with_items:
        - vsftpd.conf
    - name: Enable systemd service
      copy:
        src: lib/systemd/system/{{ item }}
        dest: /lib/systemd/system/{{ item }}
      with_items:
        - browser-protocol.service
        - browser-protocol-tunnel.service
        - vsftpd.service
      notify:
        - Reload systemd
        - Reload Browser protocol server
        - Reload Browser protocol tunnel
        - Reload vsftpd

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
    - name: Reload Browser protocol server
      service:
        name: browser-protocol
        enabled: yes
        state: restarted
    - name: Reload Browser protocol tunnel
      service:
        name: browser-protocol-tunnel
        enabled: yes
        state: restarted
    - name: Reload vsftpd
      service:
        name: vsftpd
        enabled: yes
        state: restarted
